name: Slack Notification CI

on: [push]

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v1.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
