name: Slack Notification CI

on: [push]

jobs:
  Slack Notification:
     name: Slack Notification
     runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Slack Notification
    - uses: thliang01/action-slack-notify@master
    env:
        SLACK_WEBHOOK: https://hooks.slack.com/services/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
